stages:
  - deploy

default:
  tags:
    - ec2

deploy_dev_frontend:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev-frontend"'
  script:
    - bash infra/scripts/write-env-files.sh dev-frontend
    - bash infra/scripts/deploy-dev-frontend.sh

deploy_dev_backend:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev-backend"'
  script:
    - bash infra/scripts/write-env-files.sh dev-backend
    - bash infra/scripts/deploy-dev-backend.sh

deploy_dev_ai:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev-ai"'
  script:
    - bash infra/scripts/write-env-files.sh dev-ai
    - bash infra/scripts/deploy-dev-ai.sh

deploy_develop:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  script:
    - bash infra/scripts/write-env-files.sh develop
    - bash infra/scripts/deploy-develop.sh
