services:
  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      ml-server:
        condition: service_started
    volumes:
      - ../nginx/nginx.ai.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-net

  ml-server:
    build:
      context: ../../services/ai/3_ai_server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      AI_DB_URL: postgresql+psycopg2://${APP_DB_USER}:${APP_DB_PASSWORD}@postgres:5432/${APP_DB_NAME}
    expose:
      - "8000"
    networks:
      - app-net
      - base-net

  ml-worker:
    build:
      context: ../../services/ai/1_data_pipeline/stock
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      APP_ENV: ${SPRING_PROFILE}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${APP_DB_NAME}
      DB_USER: ${APP_DB_USER}
      DB_PASSWORD: ${APP_DB_PASSWORD}
    networks:
      - app-net
      - base-net

networks:
  app-net:
    name: ${APP_NETWORK_NAME}
  base-net:
    external: true
    name: sallae-base-net
