#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "postgres" <<SQL
DO
\$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${DEV_DB_USER}') THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${DEV_DB_USER}', '${DEV_DB_PASSWORD}');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${PROD_DB_USER}') THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${PROD_DB_USER}', '${PROD_DB_PASSWORD}');
    END IF;
END
\$\$;

SELECT format('CREATE DATABASE %I OWNER %I', '${DEV_DB_NAME}', '${DEV_DB_USER}')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${DEV_DB_NAME}')
\gexec

SELECT format('CREATE DATABASE %I OWNER %I', '${PROD_DB_NAME}', '${PROD_DB_USER}')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${PROD_DB_NAME}')
\gexec

REVOKE ALL ON DATABASE ${DEV_DB_NAME} FROM PUBLIC;
REVOKE ALL ON DATABASE ${PROD_DB_NAME} FROM PUBLIC;

GRANT CONNECT ON DATABASE ${DEV_DB_NAME} TO ${DEV_DB_USER};
GRANT CONNECT ON DATABASE ${PROD_DB_NAME} TO ${PROD_DB_USER};

REVOKE CONNECT ON DATABASE ${DEV_DB_NAME} FROM ${PROD_DB_USER};
REVOKE CONNECT ON DATABASE ${PROD_DB_NAME} FROM ${DEV_DB_USER};
SQL
