ALTER TABLE ai_portfolio
    ADD COLUMN IF NOT EXISTS initial_capital BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cash_balance BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS realized_profit BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS unrealized_profit BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_asset_value BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS latest_record_date DATE;

ALTER TABLE ai_portfolio_holdings
    ADD COLUMN IF NOT EXISTS buy_date TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS avg_buy_price INTEGER,
    ADD COLUMN IF NOT EXISTS current_price INTEGER,
    ADD COLUMN IF NOT EXISTS holding_quantity BIGINT,
    ADD COLUMN IF NOT EXISTS investment_amount BIGINT,
    ADD COLUMN IF NOT EXISTS market_value BIGINT,
    ADD COLUMN IF NOT EXISTS evaluation_profit BIGINT;

ALTER TABLE ai_trading_history
    ADD COLUMN IF NOT EXISTS trade_price INTEGER,
    ADD COLUMN IF NOT EXISTS trade_quantity BIGINT,
    ADD COLUMN IF NOT EXISTS trade_amount BIGINT,
    ADD COLUMN IF NOT EXISTS realized_profit BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS holding_quantity_after BIGINT,
    ADD COLUMN IF NOT EXISTS cash_balance_after BIGINT,
    ADD COLUMN IF NOT EXISTS avg_buy_price_after INTEGER;

ALTER TABLE ai_daily_performance
    ADD COLUMN IF NOT EXISTS cash_balance BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS invested_amount BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS market_value BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS realized_profit BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS unrealized_profit BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_asset_value BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS holding_count INTEGER NOT NULL DEFAULT 0;
