-- KOSPI200 종목 데이터 시드
-- krx_sector, gics_cluster 컬럼 추가 후 200개 종목 INSERT (category 포함)

ALTER TABLE stocks ADD COLUMN IF NOT EXISTS krx_sector VARCHAR(15);
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS gics_cluster VARCHAR(20);

DELETE FROM stocks WHERE ticker = '999999';

INSERT INTO stocks (ticker, name, gics_sector, krx_sector, gics_cluster, category, market_type, is_active) VALUES
-- === cluster1: IT / Communication ===
('000660', 'SK하이닉스', 'Information Technology', '전기·전자', 'cluster1', '반도체', 'KOSPI', true),
('001440', '대한전선', 'Information Technology', '전기·전자', 'cluster1', '전자부품', 'KOSPI', true),
('002030', '아세아', 'Communication Services', '일반서비스', 'cluster1', '건설 / 인프라', 'KOSPI', true),
('003670', '포스코퓨처엠', 'Information Technology', '전기·전자', 'cluster1', '2차전지', 'KOSPI', true),
('004490', '세방전지', 'Information Technology', '전기·전자', 'cluster1', '2차전지', 'KOSPI', true),
('005250', '녹십자홀딩스', 'Communication Services', '일반서비스', 'cluster1', '금융 / 헬스케어', 'KOSPI', true),
('005930', '삼성전자', 'Information Technology', '전기·전자', 'cluster1', '반도체', 'KOSPI', true),
('006400', '삼성SDI', 'Information Technology', '전기·전자', 'cluster1', '2차전지', 'KOSPI', true),
('007340', 'DN오토모티브', 'Information Technology', '전기·전자', 'cluster1', '소비내구재', 'KOSPI', true),
('007660', '이수페타시스', 'Information Technology', '전기·전자', 'cluster1', '전자부품', 'KOSPI', true),
('009150', '삼성전기', 'Information Technology', '전기·전자', 'cluster1', '전자부품', 'KOSPI', true),
('010120', 'LS ELECTRIC', 'Information Technology', '전기·전자', 'cluster1', '전자부품', 'KOSPI', true),
('011070', 'LG이노텍', 'Information Technology', '전기·전자', 'cluster1', '전자부품', 'KOSPI', true),
('012750', '에스원', 'Communication Services', '일반서비스', 'cluster1', '유통 / 서비스', 'KOSPI', true),
('017670', 'SK텔레콤', 'Communication Services', '통신', 'cluster1', 'IT플랫폼 / 소프트웨어', 'KOSPI', true),
('018260', '삼성에스디에스', 'Information Technology', 'IT 서비스', 'cluster1', 'IT플랫폼 / 소프트웨어', 'KOSPI', true),
('021240', '코웨이', 'Communication Services', '일반서비스', 'cluster1', '소비내구재', 'KOSPI', true),
('022100', '포스코DX', 'Communication Services', '일반서비스', 'cluster1', 'IT플랫폼 / 소프트웨어', 'KOSPI', true),
('028050', '삼성E&A', 'Communication Services', '일반서비스', 'cluster1', '건설 / 인프라', 'KOSPI', true),
('030000', '제일기획', 'Communication Services', '일반서비스', 'cluster1', '유통 / 서비스', 'KOSPI', true),
('030200', 'KT', 'Communication Services', '통신', 'cluster1', 'IT플랫폼 / 소프트웨어', 'KOSPI', true),
('032640', 'LG유플러스', 'Communication Services', '통신', 'cluster1', 'IT플랫폼 / 소프트웨어', 'KOSPI', true),
('034220', 'LG디스플레이', 'Information Technology', '전기·전자', 'cluster1', '디스플레이', 'KOSPI', true),
('035420', 'NAVER', 'Information Technology', 'IT 서비스', 'cluster1', 'IT플랫폼 / 소프트웨어', 'KOSPI', true),
('035720', '카카오', 'Information Technology', 'IT 서비스', 'cluster1', 'IT플랫폼 / 소프트웨어', 'KOSPI', true),
('036570', '엔씨소프트', 'Information Technology', 'IT 서비스', 'cluster1', '게임 / 디지털콘텐츠', 'KOSPI', true),
('052690', '한전기술', 'Communication Services', '일반서비스', 'cluster1', '에너지', 'KOSPI', true),
('062040', '산일전기', 'Information Technology', '전기·전자', 'cluster1', '전자부품', 'KOSPI', true),
('064400', 'LG씨엔에스', 'Information Technology', 'IT 서비스', 'cluster1', 'IT플랫폼 / 소프트웨어', 'KOSPI', true),
('066570', 'LG전자', 'Information Technology', '전기·전자', 'cluster1', '스마트기기', 'KOSPI', true),
('066970', '엘앤에프', 'Information Technology', '전기·전자', 'cluster1', '2차전지', 'KOSPI', true),
('192080', '더블유게임즈', 'Information Technology', 'IT 서비스', 'cluster1', '게임 / 디지털콘텐츠', 'KOSPI', true),
('251270', '넷마블', 'Information Technology', 'IT 서비스', 'cluster1', '게임 / 디지털콘텐츠', 'KOSPI', true),
('259960', '크래프톤', 'Information Technology', 'IT 서비스', 'cluster1', '게임 / 디지털콘텐츠', 'KOSPI', true),
('267260', 'HD현대일렉트릭', 'Information Technology', '전기·전자', 'cluster1', '전자부품', 'KOSPI', true),
('272210', '한화시스템', 'Information Technology', '전기·전자', 'cluster1', '방산', 'KOSPI', true),
('298040', '효성중공업', 'Information Technology', '전기·전자', 'cluster1', '전자부품', 'KOSPI', true),
('307950', '현대오토에버', 'Information Technology', 'IT 서비스', 'cluster1', 'IT플랫폼 / 소프트웨어', 'KOSPI', true),
('326030', 'SK바이오팜', 'Communication Services', '일반서비스', 'cluster1', '금융 / 헬스케어', 'KOSPI', true),
('361610', 'SK아이이테크놀로지', 'Information Technology', '전기·전자', 'cluster1', '2차전지', 'KOSPI', true),
('373220', 'LG에너지솔루션', 'Information Technology', '전기·전자', 'cluster1', '2차전지', 'KOSPI', true),
('443060', 'HD현대마린솔루션', 'Communication Services', '일반서비스', 'cluster1', '조선', 'KOSPI', true),
('450080', '에코프로머티', 'Information Technology', '전기·전자', 'cluster1', '2차전지', 'KOSPI', true),

-- === cluster2: Financials ===
('000150', '두산', 'Financials', '기타금융', 'cluster2', '기타', 'KOSPI', true),
('000240', '한국앤컴퍼니', 'Financials', '기타금융', 'cluster2', '기타', 'KOSPI', true),
('000810', '삼성화재', 'Financials', '보험', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('001040', 'CJ', 'Financials', '기타금융', 'cluster2', '기타', 'KOSPI', true),
('001450', '현대해상', 'Financials', '보험', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('001800', '오리온홀딩스', 'Financials', '기타금융', 'cluster2', '기타', 'KOSPI', true),
('003030', '세아제강지주', 'Financials', '기타금융', 'cluster2', '소재', 'KOSPI', true),
('003550', 'LG', 'Financials', '기타금융', 'cluster2', '기타', 'KOSPI', true),
('004990', '롯데지주', 'Financials', '기타금융', 'cluster2', '기타', 'KOSPI', true),
('005830', 'DB손해보험', 'Financials', '보험', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('005940', 'NH투자증권', 'Financials', '증권', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('006040', '동원산업', 'Financials', '기타금융', 'cluster2', '필수소비재', 'KOSPI', true),
('006260', 'LS', 'Financials', '기타금융', 'cluster2', '기타', 'KOSPI', true),
('006800', '미래에셋증권', 'Financials', '증권', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('008930', '한미사이언스', 'Financials', '기타금융', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('009540', 'HD한국조선해양', 'Financials', '기타금융', 'cluster2', '조선', 'KOSPI', true),
('009970', '영원무역홀딩스', 'Financials', '기타금융', 'cluster2', '기타', 'KOSPI', true),
('010060', 'OCI홀딩스', 'Financials', '기타금융', 'cluster2', '기타', 'KOSPI', true),
('016360', '삼성증권', 'Financials', '증권', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('024110', '기업은행', 'Financials', '은행', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('029780', '삼성카드', 'Financials', '기타금융', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('032830', '삼성생명', 'Financials', '보험', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('034730', 'SK', 'Financials', '기타금융', 'cluster2', '기타', 'KOSPI', true),
('039490', '키움증권', 'Financials', '증권', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('055550', '신한지주', 'Financials', '기타금융', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('071050', '한국금융지주', 'Financials', '기타금융', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('078930', 'GS', 'Financials', '기타금융', 'cluster2', '에너지', 'KOSPI', true),
('086790', '하나금융지주', 'Financials', '기타금융', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('088350', '한화생명', 'Financials', '보험', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('105560', 'KB금융', 'Financials', '기타금융', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('0126Z0', '삼성에피스홀딩스', 'Financials', '기타금융', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('138040', '메리츠금융지주', 'Financials', '기타금융', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('138930', 'BNK금융지주', 'Financials', '기타금융', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('139130', 'iM금융지주', 'Financials', '기타금융', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('175330', 'JB금융지주', 'Financials', '기타금융', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('180640', '한진칼', 'Financials', '기타금융', 'cluster2', '운송 / 물류', 'KOSPI', true),
('267250', 'HD현대', 'Financials', '기타금융', 'cluster2', '기타', 'KOSPI', true),
('316140', '우리금융지주', 'Financials', '기타금융', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('323410', '카카오뱅크', 'Financials', '은행', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('377300', '카카오페이', 'Financials', '기타금융', 'cluster2', '금융 / 헬스케어', 'KOSPI', true),
('402340', 'SK스퀘어', 'Financials', '기타금융', 'cluster2', '기타', 'KOSPI', true),

-- === cluster3: Materials ===
('000210', 'DL', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('000670', '영풍', 'Materials', '금속', 'cluster3', '소재', 'KOSPI', true),
('000880', '한화', 'Materials', '화학', 'cluster3', '방산', 'KOSPI', true),
('001430', '세아베스틸지주', 'Materials', '금속', 'cluster3', '소재', 'KOSPI', true),
('002380', 'KCC', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('002790', '아모레퍼시픽홀딩스', 'Materials', '화학', 'cluster3', '패션 / 뷰티', 'KOSPI', true),
('002840', '미원상사', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('003240', '태광산업', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('004000', '롯데정밀화학', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('004020', '현대제철', 'Materials', '금속', 'cluster3', '소재', 'KOSPI', true),
('005420', '코스모화학', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('005490', 'POSCO홀딩스', 'Materials', '금속', 'cluster3', '소재', 'KOSPI', true),
('006650', '대한유화', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('008730', '율촌화학', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('009830', '한화솔루션', 'Materials', '화학', 'cluster3', '친환경 / 탄소', 'KOSPI', true),
('010130', '고려아연', 'Materials', '금속', 'cluster3', '소재', 'KOSPI', true),
('010950', 'S-Oil', 'Materials', '화학', 'cluster3', '에너지', 'KOSPI', true),
('011170', '롯데케미칼', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('011780', '금호석유화학', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('011790', 'SKC', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('014680', '한솔케미칼', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('014820', '동원시스템즈', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('017960', '한국카본', 'Materials', '금속', 'cluster3', '소재', 'KOSPI', true),
('051900', 'LG생활건강', 'Materials', '화학', 'cluster3', '패션 / 뷰티', 'KOSPI', true),
('051910', 'LG화학', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('069260', 'TKG휴켐스', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('073240', '금호타이어', 'Materials', '화학', 'cluster3', '소비내구재', 'KOSPI', true),
('079550', 'LIG넥스원', 'Materials', '금속', 'cluster3', '방산', 'KOSPI', true),
('090430', '아모레퍼시픽', 'Materials', '화학', 'cluster3', '패션 / 뷰티', 'KOSPI', true),
('093370', '후성', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('096770', 'SK이노베이션', 'Materials', '화학', 'cluster3', '에너지', 'KOSPI', true),
('103140', '풍산', 'Materials', '금속', 'cluster3', '방산', 'KOSPI', true),
('112610', '씨에스윈드', 'Materials', '금속', 'cluster3', '친환경 / 탄소', 'KOSPI', true),
('120110', '코오롱인더', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('161390', '한국타이어앤테크놀로지', 'Materials', '화학', 'cluster3', '소비내구재', 'KOSPI', true),
('161890', '한국콜마', 'Materials', '화학', 'cluster3', '패션 / 뷰티', 'KOSPI', true),
('192820', '코스맥스', 'Materials', '화학', 'cluster3', '패션 / 뷰티', 'KOSPI', true),
('268280', '미원에스씨', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('278470', '에이피알', 'Materials', '화학', 'cluster3', '패션 / 뷰티', 'KOSPI', true),
('285130', 'SK케미칼', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('298020', '효성티앤씨', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('298050', 'HS효성첨단소재', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),
('300720', '한일시멘트', 'Materials', '비금속', 'cluster3', '건설 / 인프라', 'KOSPI', true),
('457190', '이수스페셜티케미컬', 'Materials', '화학', 'cluster3', '소재', 'KOSPI', true),

-- === cluster3: Industrials ===
('000120', 'CJ대한통운', 'Industrials', '운송·창고', 'cluster3', '운송 / 물류', 'KOSPI', true),
('000270', '기아', 'Industrials', '운송장비·부품', 'cluster3', '소비내구재', 'KOSPI', true),
('000720', '현대건설', 'Industrials', '건설', 'cluster3', '건설 / 인프라', 'KOSPI', true),
('003490', '대한항공', 'Industrials', '운송·창고', 'cluster3', '운송 / 물류', 'KOSPI', true),
('005380', '현대차', 'Industrials', '운송장비·부품', 'cluster3', '소비내구재', 'KOSPI', true),
('005850', '에스엘', 'Industrials', '운송장비·부품', 'cluster3', '소비내구재', 'KOSPI', true),
('006360', 'GS건설', 'Industrials', '건설', 'cluster3', '건설 / 인프라', 'KOSPI', true),
('010140', '삼성중공업', 'Industrials', '운송장비·부품', 'cluster3', '조선', 'KOSPI', true),
('011200', 'HMM', 'Industrials', '운송·창고', 'cluster3', '운송 / 물류', 'KOSPI', true),
('011210', '현대위아', 'Industrials', '운송장비·부품', 'cluster3', '기계 / 산업장비', 'KOSPI', true),
('012330', '현대모비스', 'Industrials', '운송장비·부품', 'cluster3', '소비내구재', 'KOSPI', true),
('012450', '한화에어로스페이스', 'Industrials', '운송장비·부품', 'cluster3', '방산', 'KOSPI', true),
('017800', '현대엘리베이터', 'Industrials', '기계·장비', 'cluster3', '기계 / 산업장비', 'KOSPI', true),
('018880', '한온시스템', 'Industrials', '기계·장비', 'cluster3', '소비내구재', 'KOSPI', true),
('028670', '팬오션', 'Industrials', '운송·창고', 'cluster3', '운송 / 물류', 'KOSPI', true),
('034020', '두산에너빌리티', 'Industrials', '기계·장비', 'cluster3', '에너지', 'KOSPI', true),
('042660', '한화오션', 'Industrials', '운송장비·부품', 'cluster3', '조선', 'KOSPI', true),
('042700', '한미반도체', 'Industrials', '기계·장비', 'cluster3', '반도체', 'KOSPI', true),
('047040', '대우건설', 'Industrials', '건설', 'cluster3', '건설 / 인프라', 'KOSPI', true),
('047810', '한국항공우주', 'Industrials', '운송장비·부품', 'cluster3', '방산', 'KOSPI', true),
('051600', '한전KPS', 'Industrials', '건설', 'cluster3', '에너지', 'KOSPI', true),
('064350', '현대로템', 'Industrials', '운송장비·부품', 'cluster3', '방산', 'KOSPI', true),
('071970', 'HD현대마린엔진', 'Industrials', '기계·장비', 'cluster3', '조선', 'KOSPI', true),
('082740', '한화엔진', 'Industrials', '기계·장비', 'cluster3', '조선', 'KOSPI', true),
('086280', '현대글로비스', 'Industrials', '운송·창고', 'cluster3', '운송 / 물류', 'KOSPI', true),
('204320', 'HL만도', 'Industrials', '운송장비·부품', 'cluster3', '소비내구재', 'KOSPI', true),
('241560', '두산밥캣', 'Industrials', '기계·장비', 'cluster3', '기계 / 산업장비', 'KOSPI', true),
('329180', 'HD현대중공업', 'Industrials', '운송장비·부품', 'cluster3', '조선', 'KOSPI', true),
('375500', 'DL이앤씨', 'Industrials', '건설', 'cluster3', '건설 / 인프라', 'KOSPI', true),
('454910', '두산로보틱스', 'Industrials', '기계·장비', 'cluster3', '기계 / 산업장비', 'KOSPI', true),

-- === cluster3: Consumer Discretionary ===
('004170', '신세계', 'Consumer Discretionary', '유통', 'cluster3', '유통 / 서비스', 'KOSPI', true),
('007070', 'GS리테일', 'Consumer Discretionary', '유통', 'cluster3', '유통 / 서비스', 'KOSPI', true),
('008770', '호텔신라', 'Consumer Discretionary', '유통', 'cluster3', '유통 / 서비스', 'KOSPI', true),
('009240', '한샘', 'Consumer Discretionary', '유통', 'cluster3', '소비내구재', 'KOSPI', true),
('023530', '롯데쇼핑', 'Consumer Discretionary', '유통', 'cluster3', '유통 / 서비스', 'KOSPI', true),
('026960', '동서', 'Consumer Discretionary', '유통', 'cluster3', '필수소비재', 'KOSPI', true),
('028260', '삼성물산', 'Consumer Discretionary', '유통', 'cluster3', '건설 / 인프라', 'KOSPI', true),
('034230', '파라다이스', 'Consumer Discretionary', '오락·문화', 'cluster3', '유통 / 서비스', 'KOSPI', true),
('035250', '강원랜드', 'Consumer Discretionary', '오락·문화', 'cluster3', '유통 / 서비스', 'KOSPI', true),
('047050', '포스코인터내셔널', 'Consumer Discretionary', '유통', 'cluster3', '유통 / 서비스', 'KOSPI', true),
('069960', '현대백화점', 'Consumer Discretionary', '유통', 'cluster3', '유통 / 서비스', 'KOSPI', true),
('081660', '미스토홀딩스', 'Consumer Discretionary', '유통', 'cluster3', '유통 / 서비스', 'KOSPI', true),
('111770', '영원무역', 'Consumer Discretionary', '유통', 'cluster3', '패션 / 뷰티', 'KOSPI', true),
('114090', 'GKL', 'Consumer Discretionary', '오락·문화', 'cluster3', '유통 / 서비스', 'KOSPI', true),
('139480', '이마트', 'Consumer Discretionary', '유통', 'cluster3', '유통 / 서비스', 'KOSPI', true),
('282330', 'BGF리테일', 'Consumer Discretionary', '유통', 'cluster3', '유통 / 서비스', 'KOSPI', true),
('352820', '하이브', 'Consumer Discretionary', '오락·문화', 'cluster3', '게임 / 디지털콘텐츠', 'KOSPI', true),
('383220', 'F&F', 'Consumer Discretionary', '섬유·의류', 'cluster3', '패션 / 뷰티', 'KOSPI', true),

-- === cluster3: Health Care ===
('000100', '유한양행', 'Health Care', '제약', 'cluster3', '금융 / 헬스케어', 'KOSPI', true),
('003090', '대웅', 'Health Care', '제약', 'cluster3', '금융 / 헬스케어', 'KOSPI', true),
('006280', '녹십자', 'Health Care', '제약', 'cluster3', '금융 / 헬스케어', 'KOSPI', true),
('009420', '한올바이오파마', 'Health Care', '제약', 'cluster3', '금융 / 헬스케어', 'KOSPI', true),
('068270', '셀트리온', 'Health Care', '제약', 'cluster3', '금융 / 헬스케어', 'KOSPI', true),
('069620', '대웅제약', 'Health Care', '제약', 'cluster3', '금융 / 헬스케어', 'KOSPI', true),
('128940', '한미약품', 'Health Care', '제약', 'cluster3', '금융 / 헬스케어', 'KOSPI', true),
('137310', '에스디바이오센서', 'Health Care', '의료·정밀기기', 'cluster3', '금융 / 헬스케어', 'KOSPI', true),
('185750', '종근당', 'Health Care', '제약', 'cluster3', '금융 / 헬스케어', 'KOSPI', true),
('207940', '삼성바이오로직스', 'Health Care', '제약', 'cluster3', '금융 / 헬스케어', 'KOSPI', true),
('302440', 'SK바이오사이언스', 'Health Care', '제약', 'cluster3', '금융 / 헬스케어', 'KOSPI', true),

-- === cluster3: Consumer Staples ===
('000080', '하이트진로', 'Consumer Staples', '음식료·담배', 'cluster3', '필수소비재', 'KOSPI', true),
('001680', '대상', 'Consumer Staples', '음식료·담배', 'cluster3', '필수소비재', 'KOSPI', true),
('003230', '삼양식품', 'Consumer Staples', '음식료·담배', 'cluster3', '필수소비재', 'KOSPI', true),
('004370', '농심', 'Consumer Staples', '음식료·담배', 'cluster3', '필수소비재', 'KOSPI', true),
('005300', '롯데칠성', 'Consumer Staples', '음식료·담배', 'cluster3', '필수소비재', 'KOSPI', true),
('007310', '오뚜기', 'Consumer Staples', '음식료·담배', 'cluster3', '필수소비재', 'KOSPI', true),
('033780', 'KT&G', 'Consumer Staples', '음식료·담배', 'cluster3', '필수소비재', 'KOSPI', true),
('097950', 'CJ제일제당', 'Consumer Staples', '음식료·담배', 'cluster3', '필수소비재', 'KOSPI', true),
('271560', '오리온', 'Consumer Staples', '음식료·담배', 'cluster3', '필수소비재', 'KOSPI', true),
('280360', '롯데웰푸드', 'Consumer Staples', '음식료·담배', 'cluster3', '필수소비재', 'KOSPI', true),

-- === cluster3: Utilities ===
('015760', '한국전력', 'Utilities', '전기·가스', 'cluster3', '에너지', 'KOSPI', true),
('036460', '한국가스공사', 'Utilities', '전기·가스', 'cluster3', '에너지', 'KOSPI', true),
('071320', '지역난방공사', 'Utilities', '전기·가스', 'cluster3', '에너지', 'KOSPI', true)
ON CONFLICT (ticker) DO UPDATE SET
    name = EXCLUDED.name,
    gics_sector = EXCLUDED.gics_sector,
    krx_sector = EXCLUDED.krx_sector,
    gics_cluster = EXCLUDED.gics_cluster,
    category = EXCLUDED.category,
    market_type = EXCLUDED.market_type,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();